apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.appName }}-{{ .Values.namespace }}
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/chandupakkurthi-hash/nobroker-manifests.git'
    targetRevision: HEAD
    path: microservices/microservice-chart
    helm:
      valueFiles:
        - ../env/{{ .Values.namespace }}/{{ .Values.appName }}.yaml

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .Values.namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
